sudo: false
dist: trusty

language: php

notifications:
  email:
    on_success: never
    on_failure: change

cache:
  directories:
    - $HOME/.composer/cache
    - node_modules
    - vendor

matrix:
  include:
    - php: 7.4
      env: WP_VERSION=latest
    - php: 7.3
      env: WP_VERSION=latest
    - php: 7.2
      env: WP_VERSION=latest
    - php: 7.2
      env: WP_VERSION=5.3 WP_PULUGIN_DEPLOY=1
    - php: 7.2
      env: WP_VERSION=trunk
    - php: 7.2
      env: WP_TRAVISCI=phpcs

before_script:
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - |
    if [ -f ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini ]; then
      phpenv config-rm xdebug.ini
    else
      echo "xdebug.ini does not exist"
    fi
  - |
  - composer install
  - nvm install --lts
  - npm install
script:
  - npm run build
  - |
    if [[ ! -z "$WP_VERSION" ]] ; then
      composer test
      WP_MULTISITE=1 composer test
    fi
  - |
    if [[ "$WP_TRAVISCI" == "phpcs" ]] ; then
      composer phpcs
    fi
after_success:
  - bash bin/deploy.sh

